version: "3.3"

services:

  tnr-frontend:
    build: './angular-src'
    ports:
      - "4200:4200"
      - "49153:49153"
    networks:
      - backend
    depends_on:
      - tnr-server
    volumes:
      - ./angular-src:/home/node/client/
      - /home/node/client/node_modules

  tnr-server:
    build: './server'
    ports:
     - "8080:8080"
    networks:
     - backend
    depends_on:
     - tnr-database
    env_file:
     - ./server/.env
    volumes:
     - ./server:/home/node/server/
     - /home/node/server/node_modules

  tnr-database:
    image: postgres:latest
    ports:
     - "5436:5432"
    networks:
     - backend

networks:
  backend: